<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-PUJJMK1" failures="1" tests="5" name="Test" time="96.128" errors="0" timestamp="11 Mar 2024 07:01:00 GMT">
  <testcase classname="com.scenario.automate.HandleAlertTests" name="cancelAlertTest" time="9.609"/>
  <testcase classname="com.scenario.automate.HandleAlertTests" name="handleAlertTest" time="2.001"/>
  <testcase classname="com.scenario.automate.HandleAlertTests" name="sendAlertMessageTest" time="3.92"/>
  <testcase classname="com.scenario.automate.HandleAlertTests" name="testClosePopUp" time="5.878">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.scenario.automate.HandleAlertTests.testClosePopUp(HandleAlertTests.java:113)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- testClosePopUp -->
  <testcase classname="com.scenario.automate.HandleAlertTests" name="testModalOpenAndClose" time="62.042"/>
</testsuite> <!-- Test -->
