<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-PUJJMK1" failures="1" tests="5" name="com.scenario.automate.HandleAlertTests" time="83.450" errors="0" timestamp="11 Mar 2024 07:01:00 GMT">
  <testcase classname="com.scenario.automate.HandleAlertTests" name="sendAlertMessageTest" time="3.920"/>
  <testcase classname="com.scenario.automate.HandleAlertTests" name="handleAlertTest" time="2.001"/>
  <testcase classname="com.scenario.automate.HandleAlertTests" name="testModalOpenAndClose" time="62.042"/>
  <testcase classname="com.scenario.automate.HandleAlertTests" name="testClosePopUp" time="5.878">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:288)
	at org.testng.Assert.assertEquals(Assert.java:298)
	at com.scenario.automate.HandleAlertTests.testClosePopUp(HandleAlertTests.java:113)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- testClosePopUp -->
  <testcase classname="com.scenario.automate.HandleAlertTests" name="cancelAlertTest" time="9.609"/>
</testsuite> <!-- com.scenario.automate.HandleAlertTests -->
